### ISSUE TITLE
CDF or Heroku?

### ISSUE THREAD

**Issue by g3wanghc** [cssu/cssu.ca-old#51]
CDF is being glitchy. Should we use Heroku instead?

@elliottsj @arkon @xMrWhite

**Comment by arkon** [comment]
I vote for CDF just to keep it on a school-related system, since the group of CSSU people maintaining it will be changing every year.

**Comment by elliottsj** [comment]
I'd vote Heroku because it's much simpler to manage deployments. We already need to pass along access to the GitHub org anyway every year, so transferring Heroku access shouldn't be a big concern. Main issue is that Heroku orgs are enterprise-only, so those with Heroku access would have to share a personal Heroku account.

**Comment by elliottsj** [comment]
Closed via #52
